phasehq/console

README.md

Updated slack invite to Phase community 
```sh
```

Update: slack invite

---

.github/workflows/docker_builds.yml

Deploy docker images to ghcr

---

.github/workflows/docker_builds.yml

Build and push Docker images to AWS ECR along with Docker Hub & ghcr. This will be helpful for containers to AWS services that only support deployments from ECR.
```sh
```

Build and push docker images to AWS ECR

---

.github/workflows/docker_builds.yml

Fix: AWS ECR config

---

.env.dev.example
.env.example
.gitignore
.vscode/settings.json
CONTRIBUTING.md
README.md
backend/Dockerfile.dev
dev-docker-compose.yml
docker-compose.yml
frontend/Dockerfile.dev

A docker based development environment that matches production runtime and supports devserver hotloading.

feat: Docker dev setup

---

README.md

Reduced the size of the title in the readme to work better on mobile and smaller screens.

chore: smaller repo title in readme

---

README.md

Minor fixes to typos and grammar in readme

chore: minor fixes to readme

---

frontend/Dockerfile

This PR improves the runtime security of the frontend next.js app by running it as a non-root (app) user. The backend already uses this technique.

Run the frontend app as a non-root user

---

frontend/app/invite/[invite]/page.tsx
frontend/app/signup/page.tsx

Updated the on-boarding screen copy to make it more accurate.

updated: signup and invite link recovery phase copy

---

frontend/components/environments/SecretRow.tsx

Fixed null history for new secret

fix: handle no secret history for new secret

---

backend/api/views.py

Fixes an issue with logging read events when using a service token

fix: GET secrets with service token

---

backend/backend/graphene/mutations/organisation.py

Removes the restriction on creating new orgs for existing org owners.

feat: remove one org limit per user

---

backend/ee/feature_flags.py
frontend/components/apps/NewAppDialog.tsx

Updates the free tier app limit

feat: update free tier app limit

---

.github/ISSUE_TEMPLATE/feature_request.md
frontend/app/layout.tsx
frontend/package.json
frontend/yarn.lock

Fix  toastify css

---

backend/Dockerfile
frontend/Dockerfile

Added curl as a system system dependency. This is helpful for setting up things like container health checks.

feat: added curl as a system dependency in frontend & backend Dockerfile

---

frontend/app/[team]/tokens/page.tsx
frontend/app/invite/[invite]/page.tsx
frontend/app/webauth/[requestCode]/page.tsx
frontend/app/webauth/page.tsx
frontend/next.config.js
frontend/utils/auth.ts

Adds webauth flow to authenticate with the CLI. 
Do not merge before: https://github.com/phasehq/cli/pull/69

feat: webauth

---

frontend/components/logs/SecretLogs.tsx

Correctly mask secret keys in the logs table

fix: log screen mask

---

frontend/app/[team]/apps/[app]/settings/page.tsx
frontend/app/[team]/apps/page.tsx
frontend/components/apps/DeleteAppDialog.tsx
frontend/components/apps/NewAppDialog.tsx

Made misc ui fixes and improvements to creating and deleting apps. Reworked app settings screen.
* Made button bigger, added label
* Made entire card clickable
* Updated hover states
* Buttons now show loading states
* Cancel / close buttons are not clickable when loading state is active
* Restyled app settings screen to match style of account settings
* Added basic app metadata
* Updated delete button variants to `danger`
* Added loading states when deleting an app

fix: misc improvements to app ui

---

backend/backend/graphene/types.py

Fix the query for resolving personal secrets

fix: org member query in resolver for personal secrets

---

frontend/components/layout/Sidebar.tsx

This pull request introduces a new feature: the addition of a "Create New Organization" button, related to the issue (#113)
This feature is to provide users with a convenient way to create a new organization within the application. The button will streamline the process, making it more intuitive and user-friendly.

feat: create new organisation button

---

backend/api/serializers.py
backend/logs/queries.py

Updates the Secret serializer to return tag names in the `tags` field

feat: return tag names in secret serializer

---

backend/backend/schema.py

Ensures that app environments are always sorted as [dev, staging, prod]. Should fix the order of envs in the following screens:
* Secrets overview tab
* Env switch dropdown menu
* Service token env selection field
* Create sync env selection radios

fix: sort returned environments by type

---

frontend/components/apps/NewAppDialog.tsx

Log exception errors to browser console when creating a new app

fix: log app create errors to console

---

frontend/next.config.js

This adds `https://session.phase.dev;` to the CSP
```sh
```

fix: CSP on phase domains

---

frontend/app/[team]/apps/[app]/page.tsx

Adds an empty state to the secrets tab

feat: add empty state to secrets overview tab

---

frontend/app/[team]/page.tsx
frontend/components/syncing/IntegrationsHomeCard.tsx
frontend/components/users/MembersHomeCard.tsx

Adds members and integrations cards to organisation home:

feat:  add cards to org home

---

frontend/Dockerfile
frontend/scripts/replace-variable.sh
frontend/scripts/start.sh

#C Description 📣
Refactors the public env var script for frontend to avoid repetition and make it more easily extensible

chore:  simplify public env script

---

frontend/package-lock.json
frontend/package.json
frontend/yarn.lock

Bumped posthog version to `1.104.4`.

chore: bump posthog version

---

backend/api/utils/secrets.py
backend/api/views.py
backend/backend/graphene/mutations/environment.py
backend/backend/graphene/mutations/syncing.py

Ensures that path strings are always normalized with the following rules:
* Leading `/` is present
* Trailing `/` is not present
* No repeated `/` are allowed

feat: normalize path strings

---

frontend/components/onboarding/TeamName.tsx

fix: bad import

---

frontend/app/[team]/apps/[app]/page.tsx
frontend/app/[team]/integrations/page.tsx
frontend/app/[team]/page.tsx
frontend/components/apps/AppCard.tsx
frontend/components/common/Card.tsx
frontend/components/environments/secrets/SecretPropertyDiffs.tsx

Fix all Text overflow on Dashboard 
Fixes #134 
Manual testing by visiting and reviewing UI components making sure the render text correctly
```sh
```

fix: text overflow

---

.github/pull_request_template.md

Updates the PR template to encourage better documented PRs and release notes

chore:  update PR template

---

frontend/scripts/replace-variable.sh

The `replace-variable.sh` script currently runs on the entire JavaScript bundle
Use grep to match files that contain the `BAKED_` prefix and  speed up the script, and this container start time
Fixes #203 
Current:
```
real    0m8.029s
user    0m0.069s
sys     0m0.059s
```
With grep:
```
real    0m1.905s
user    0m0.066s
sys     0m0.035s
```
* Improved frontend container startup time by optimizing replace-variable script
Many thanks to @firemuzzy for the suggestion

feat: speed up replace variable script

---

frontend/components/layout/Sidebar.tsx

Fix organization dropdown text overflow. Fixes #196  
Add text truncation
Truncate long text in organization Dropdown
*If there are aspects of the changes that you're unsure about or would like feedback on, list them here.*
Manual testing

fix: text overflow 

---

frontend/app/lockbox/[boxId]/error.tsx
frontend/app/lockbox/[boxId]/layout.tsx
frontend/app/lockbox/[boxId]/page.tsx

Adds page title and description for lockbox routes
* Added a `layout.tsx` for `/lockbox` routes, with a custom title and description
* Moved common layout components to layout
Updated page meta for lockbox routes

feat: add lockbox layout with meta

---

frontend/app/signup/page.tsx

Fixes a typo on the signup page, and updates the copy based on the new keyring workflow
Fixed a typo on the signup page

fix: typo on signup page

---

frontend/components/layout/Sidebar.tsx

Fixes border width around the "Settings" button in the sidebar
Before
After
Fixed border width around the "Settings" button in the sidebar

fix: sidebar border width

---

backend/api/utils/secrets.py
backend/api/views.py

The REST api used by the CLI and SDK does not check for duplicate keys via the `key_digest` property before creating or updating secrets
Check for duplicate `path`,  `key_digest` pairs in the request payload as well as in the target env before creating or updating secrets.
If a collision is found, the api returns  status `409` with the following JSON:
```
{"error": "Duplicate secret found"}
```
Added server-side validation to prevent duplicate keys being created at the same path.
This constraint could not be added as a `unique_together` clause at the model layer since we don't have a reliable way to handle any exsiting data that may have a collision. 
Via the REST API:
* Try creating a single secret with the same key + path as an existing secret -> Expect 409
* Try creating multiple …

fix: [REST] check for duplicate secret keys in POST and PUT api methods

---

frontend/app/[team]/layout.tsx
frontend/app/webauth/[requestCode]/page.tsx
frontend/components/layout/Navbar.tsx
frontend/components/layout/Sidebar.tsx

Misc updates to the console background and shell styles
* Remove glow effect from org workspaces
* Updates sidebar active link style
Updated console background and navigation styling

feat: update console background and navigation styling

---

frontend/components/apps/tokens/CreateServiceTokenDialog.tsx
frontend/components/apps/tokens/CreateUserTokenDialog.tsx
frontend/utils/appConfig.ts

Misc fixes for the API token dialog for PATs and service tokens
* Updated the code snippet to correctly use `api.phase.dev` as the hostname on cloud
* Added `v1` prefix api endpoint
* Updated docs link to api docs
* Misc fixes to the API token dialog

fix: update token code snippet, docs link

---

docker-compose.yml

Fixes the environment variables for frontend and backend in the `docker-compose.yml`
* Move `OAUTH_REDIRECT_URI` to backend
* Update `BACKEND_API_BASE` to use the public instance url
Fixed the docker-compose config for self-hosting

fix: self hosting env

---

frontend/package.json
frontend/yarn.lock

chore: bump next to 14.2.3

---

frontend/app/[team]/settings/page.tsx
frontend/components/UserMenu.tsx
frontend/components/common/Avatar.tsx
frontend/components/layout/OnboardingNavbar.tsx

Misc improvements to the user menu for easier navigation to common settings and info
* Add details of currently logged in user to menu
* Add dark mode toggle to menu
* Add link to settings + restyled sign out button to menu
* Added a fallback to the `Avatar` component for when user avatar path is unavailable
* Add separate "App" tab in settings for app-related settings
* Restyled the user menu provide more information and quick access to common settings
* Moved app-related settings to Settings -> App
* Added a fallback for user avatar when the image is unavailable

feat: improve user menu

---

backend/Dockerfile.dev

This pull request addresses a dependency issue in the development Dockerfile. The current configuration is outdated and needs updates to ensure compatibility and smooth operation of the development environment.
- Updated the base Python image to `python:3.12.1-alpine3.19`.
- Added SHA256 checksum for security.
- Adjusted the `CMD` command to `0.0.0.0:8000` for better compatibility.
N/A
- Updated base Python image to version 3.12.1.
- Improved security by adding SHA256 checksum.
None
- Verified the Docker dev build process.
- Ensured the application runs correctly with the new base image.
- Review changes in `backend/Dockerfile.dev`.
None
1. Pull the branch.
2. Build the Docker image using the updated Dockerfile.
3. Run the container and verify the application starts correctly.

fix: dev docker file dependency issue

---

CONTRIBUTING.md

This pull request aims to enhance our contributing guidelines by including detailed instructions on setting up the Phase CLI. This addition will help new contributors get started more quickly and efficiently with our development environment.
- Add a new section "Set Up the Phase CLI" to the contributing guidelines
- Include step-by-step instructions for installing the CLI
- Provide guidance on creating a personal access token
- Detail the process of logging in via the CLI
- Add a new common issue related to CLI errors and how to debug them
- Added comprehensive instructions for setting up and using the Phase CLI in the contributing guidelines
- Included a new troubleshooting tip for CLI-related errors
Please focus on:
- The clarity and completeness of the new CLI setup instructions
- The …

feat: added cli getting started instructions in CONTRIBUTING.md

---

frontend/components/auth/UnlockKeyringDialog.tsx

On trusted browsers, the keyring unlock dialog pops up for 0.5 - 1 second while the keyring is being decrypted. During this period, the user sees the standard unlock UI, including an input field and a disabled unlock button in a loading state, even though the password is saved and the user need not interact with these form controls. 
Show an alternate UI for trusted browsers, with a simple loading spinner and text to inform users that their account keys are being initialized. 
[Screencast from 07-29-2024 07:48:41 PM.webm](https://github.com/user-attachments/assets/437c5345-6058-41b5-ae97-f984c8bfc65b)
Improve the UX for unlocking the user keyring on trusted browsers.
* Check that the dialog works as intended for both trusted and non-trusted browsers
* Check that the dialog correctly falls …

feat: improve the keyring unlock ux for trusted devices

---

frontend/package.json
frontend/yarn.lock

Updated posthog dependency to version `1.150.1`

bump: posthog version

---

frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx

Made a few quality of life changes and improvement to the secret UI. 
- Updated navigation elements to use `~/` instead of `/` .
- Added labels to navigation buttons for improved usability. (Back, Discord changes)
Before the changes (application folder path UI):
After the changes (application folder path UI):
Before the changes (state reset UI):
After the changes (state reset UI):
- Enhanced navigation elements with `~/`.
- Added button labels for better navigation.
- Introduced red button variant for discard actions.
- Manual testing on different browsers and devices.
- Verified the app builds locally.
- Check the updated navigation elements in `page.tsx`.
- Verify button style changes and label additions.
- Related discussions on navigation clarity for developers.
1. Pull the branch.
2. …

feat: misc secret screen ui improvements

---

frontend/app/[team]/apps/[app]/page.tsx
frontend/components/layout/Sidebar.tsx

* Updated the sidebar org menu button style
* Updated the icon used for the environment card re-order action
* Minor UI updates

feat: minor ui updates to sidebar,  env cards

---

backend/backend/graphene/types.py

Fixes the ordering of environments returned by the `environments` field in the `AppType` resolver
Fixed the dispayed order or environments on various screens
Check that the order of environments is correct on AppCards

fix: environments order

---

frontend/components/layout/Sidebar.tsx

The current Sidebar component displays a downward chevron for the organization switcher even when there's only one organization available. This can be confusing for users as it implies there are more options when there aren't. This PR aims to address this issue by only showing the chevron when multiple organizations are available to switch between.
- Modified the `OrgsMenu` component in `Sidebar.tsx` to conditionally render the chevron icon based on the number of available organizations.
- Utilized the existing `showOrgsMenu` variable to control the chevron's visibility.
- No changes to the component's overall structure or functionality beyond this specific UI improvement.
Single org:
https://github.com/user-attachments/assets/15eeb940-59fd-44bc-8d32-dff4c5601871
Multi orgs: …

fix: only show the dropdown chevron when there are multiple orgs

---

frontend/app/[team]/apps/page.tsx
frontend/app/[team]/members/page.tsx
frontend/components/apps/NewAppDialog.tsx
frontend/components/common/CommandPalette.tsx
frontend/components/common/Input.tsx
frontend/components/layout/Navbar.tsx

Added a command pallet and a search box in the nav bar.. Fixes #304 
Added a command palette for common actions and navigation around the console via keyboard shortcuts

feat: command palette

---

frontend/app/[team]/layout.tsx
frontend/app/globals.css
frontend/app/layout.tsx

The styling of the current toasts doesn't match the design language of the Console.
* Use dark or light theme toasts based on the active theme in the Console
* Update the toast colors to match the Console theme
* Stack multiple toasts together to reduce the screen real estate taken up by toasts
* Reduce the default delay for toasts from 5s -> 4s
https://github.com/user-attachments/assets/a31d077c-a48c-4f4c-9592-677c6814771a
Updated the styling and behavior of toasts
You can drop these buttons anywhere in to quickly test the different toast variants and behavior:
```jsx
<div className="flex gap-4">
<Button variant="primary" onClick={() => toast.success('Success! That worked!')}>
Success
</Button>
<Button variant="secondary" onClick={() => toast.info('This is some non-actionable info')}> …
```

feat: better toasts

---

frontend/components/apps/NewAppDialog.tsx
frontend/components/environments/CreateEnvironmentDialog.tsx
frontend/components/layout/Sidebar.tsx

Fixes several bugs with the client-side validation of usage limits.

fix: check for limits and usage from organisation.planDetail

---

backend/ee/billing/graphene/mutations/stripe.py

Adds a 30-day trial period for users upgrading to pro via stripe self-checkout

chore: add trial period for pro self-checkout

---

frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx
frontend/components/common/GenericDialog.tsx
frontend/components/environments/secrets/DeployPreview.tsx

Misc cleanup for the new depoy preview component, and updated styling and layout for the deploy states
* Fixes and cleanup to `DeployPreview`
* Simplified the rendering logic for diffs
* Cleaned up typography, light theme fixes
* Removed js-base truncation
* Added posthog masking
* Updated UI for deploy states
* Changed button variants for various states to better align with required user action: deployed -> secondary, deploy required -> primary 
* Added icon for "Deploy" state
* Moved "undeployed changes made" alert banner above deploy button
* Updated alert copy to include number of changes
* Updated alert variant to `info`
https://github.com/user-attachments/assets/284b1898-1edb-476f-bb6a-a7a33e1266ca
Misc updates and improvements to UX for deploying secret changes
~~- [ ] Update …

feat: deploy ux updates

---

.github/workflows/docker_builds.yml
backend/Dockerfile

This PR adds support for building the project for ARM64 architectures and updates the dependencies in the GitHub Actions workflow. The change ensures compatibility across different platforms, addressing issues with cross-architecture builds.
- Implement ARM64 builds.
- Update actions dependencies to improve workflow performance and compatibility.
- Refactor Dockerfile and build scripts to accommodate multi-stage builds.
- **New**: Support for ARM64 builds.
- **Updated**: Dependencies in GitHub Actions.

feat: arm64 builds, updated actions dependencies

---

backend/api/emails.py
frontend/components/common/CommandPalette.tsx
frontend/components/layout/Sidebar.tsx

Fixes various broken links
* Removed extra settings menu item from sidebar
* Fixed members link in comand pallete
* Fixed members link in email template

fix: links

---

backend/api/utils/access/roles.py

Minor changes and improvements to Phase Managed RBAC Role descriptions to improve grammar and consistency.

Feat  service accounts service role description

---

frontend/components/dashboard/CliInstallCommands.tsx

Fixed various bugs and inconsistencies in the CLI install instructions guide in getting started component.
- Windows
- Python Pip
- Alpine linux

fix: CLI install instructions

---

backend/api/templates/base.html

Updates the year in the email footer template

chore: update date in email footer

---

frontend/app/[team]/apps/[app]/access/service-accounts/page.tsx

fix: service account copy typo

---

frontend/app/[team]/access/service-accounts/[account]/_components/DeleteServiceAccountTokenDialog.tsx
frontend/app/[team]/access/service-accounts/[account]/page.tsx
frontend/utils/tokens.ts

Improves the UX for Service account tokens
* Added a loading state to the "Delete" button when deleting a token
* Make expired tokens more evident by:
* Red text color on expiry timestamp
* "Expired" label instead of "Expires"
Improved the UX for managing Service Account Tokens by adding a delete loading state, and better display for expired tokens

fix: service account token ux

---

frontend/app/[team]/apps/[app]/_components/AppEnvironments.tsx
frontend/app/[team]/apps/[app]/_components/AppSecretRow.tsx
frontend/app/[team]/apps/[app]/_components/AppSecrets.tsx

Improves the typography, responsiveness and layout of the cross-env table to make sure keys are always visible on smaller screens, or where there are a large number of environments
Fixes #514 
* Added a minimum width to the key column based on screen width
* Tweaked typography to be more responsive
* Condense env name headers for smaller screen sizes
* Add horizontal scroll to table
https://github.com/user-attachments/assets/a7d4639f-6d4d-4905-8aae-91362719aa67
Improved the visiblity of secret keys in the cross-env table for smaller screen sizes, or when there are a large number of environments

fix: improve key visibility and space usage in cross env table

---

backend/api/views/secrets.py

Adds support for filtering secrets by tags over the REST API
Docs: https://github.com/phasehq/docs/pull/150
Add an optional `tags` query param, which takes a comma separated list of tags. 
Fetch all secrets in the Development environment tagged as `postgres`:
`'/public/v1/secrets/?app_id=<app_id>&env=Development&tags=postgres'`
Fetch all secrets tagged with either `postgres` or `aws`
`'/public/v1/secrets/?app_id=<app_id>&env=Development&tags=postgres,aws'`
Added tag filtering support to the Secrets API

feat: allow filtering secrets by tag

---

frontend/components/environments/CreateEnvironmentDialog.tsx

Fix typo in create new environment popup.

fix: typo in environment access alert

---

backend/api/serializers.py
backend/api/tasks.py
backend/api/utils/access/permissions.py
backend/api/utils/secrets.py
backend/api/utils/syncing/secrets.py
backend/api/views/secrets.py
frontend/components/syncing/SyncHistory.tsx

Adds cross-app secret referencing, refactors job syncing code to more gracefully handle exceptions
Docs: https://github.com/phasehq/docs/pull/149
1. Added  cross-app referencing support
Cross-app references can be constructed by prefixing a reference string by the app name followed by `::`, eg: `${api::staging.API_URL}`
References are resolved over the API if the user / services account making the request has access to the respective app + env. If they do not have access, the specific reference is not resolved and the value is returned with the reference syntax as is.
References are resolved when syncing to third-party services as long as the app being referenced has SSE enabled. If SSE is not enabled, the resolution fails and the sync will fail
2. Updated third-party syncing failure …

feat: add cross-app secret referencing

---

backend/api/auth.py

feat: improve REST api exception and error logging

---

backend/api/utils/access/middleware.py

Fixes an edge case with legacy service tokens in the IP allowlist middleware for the REST api
Fixed the IP allowlist middleware for legacy service tokens

fix: handle legacy tokens in rest api ip allowlist middleware

---

frontend/package.json
frontend/yarn.lock

chore: bump posthog

---

LICENSE
backend/api/templates/base.html
backend/ee/LICENSE
frontend/ee/LICENSE

Update co name on licenses and email footer

chore: update co name

---

frontend/app/login/page.tsx
frontend/components/InstanceInfo.tsx
frontend/components/VersionLabel.tsx
frontend/components/auth/SignInButtons.tsx

Misc changes and improvements to the login screen improvements PR https://github.com/phasehq/console/pull/619
1. Don't show terms of service and privacy policy links when running on self-hosted infra (non Phase Cloud)
2. Handled cases when `SSO_PROVIDERS` may not be provided or is blank
3. Removed version from version label
4. Added region indicator with EU logo 
When `SSO_PROVIDERS` is not supplied or blank:

feat: misc changes to improve signin screen 

---

frontend/package.json
frontend/yarn.lock

This PR bumps PostHog version.

chore(deps): update posthog-js to version 1.258.3
