phasehq/console

backend/api/emails.py, backend/api/views.py
Fixes the OAuth provider name in email login alerts.
=> fix: update auth provider in email alerts

frontend/app/[team]/layout.tsx
Fix to correctly handle vertical overflow in the team root layout. Resolves issue #71 
[Screencast from 10-12-2023 10:40:54 AM.webm](https://github.com/phasehq/console/assets/6710327/816bf76c-1303-4885-8fe7-3bd054728eb9)
=> fix: handle vertical overflow in team layout

frontend/components/apps/NewAppDialog.tsx
Adds the missing `DB_USER` secret to the example secrets. Fixes #73
=> fix: add mising example secret

frontend/app/layout.tsx, frontend/package.json, frontend/yarn.lock
Resolves an issue with the react-toastify css import that was breaking the frontend build.
=> fix: react toastify css import

.env.dev.example
Fixes the protocol for nextauth url, oauth redirect uri and cors allowed origins in the dev env.
=> fix: protocols in dev env

backend/backend/graphene/types.py, frontend/components/environments/SecretRow.tsx
Updates the secret history resolver to only fetch 'Create' and 'Update' events, and removed the client side filter based on event type. This should speed up client-side performance for secrets with a large number of read events.
=> fix: only fetch create and update events in secret history query

backend/backend/settings.py
Bumps the session cookie TTL to 1 week.
=> feat: bump session cookie ttl to 1 week

frontend/app/globals.css
This pull request addresses and resolves the issue of overlapping password icons (#102) specifically observed in the Edge browser. The issue was causing icons appearing on top of each other, leading to a poor user experience.
=> fix: overlapping password icons | Edge Browser

frontend/app/[team]/apps/[app]/page.tsx
Fixes the search UI for the light theme (#74)
- for light theme
- for dark theme
=> fix: Search UI for light theme

frontend/package.json, frontend/yarn.lock
Bumps the posthog SDK version to `1.91.1`
=> chore: bump posthog sdk version

backend/requirements.txt, frontend/package.json, frontend/yarn.lock
This bumps the following dependencies:
- Frontend - Posthog
- Backend - Cryptography to address - https://github.com/phasehq/console/security/dependabot/42
I have build and tested critical parts of the console with the new dependency versions.
```sh
```
=> Chore: bump dependencies

backend/api/utils/syncing/secrets.py
Fixes an issue when resolving local references, if the referenced env or secret cannot be found.
=> fix: fallback to raw value when reference cannot be resolved

frontend/components/syncing/CreateProviderCredentialsDialog.tsx
Fixes the button type for the "Help" button in `CreateProviderCredentialsDialog`
=> fix: help button type in provider creds dialog

frontend/components/environments/SecretRow.tsx
Prevents spaces from being used in secret keys
=> fix: disallow spaces in secret names

frontend/components/environments/SecretRow.tsx
Allows switching between key and value fields for secrets using `Tab`
[Screencast from 01-22-2024 06:33:22 PM.webm](https://github.com/phasehq/console/assets/6710327/460cedbc-446d-4074-912d-baa0894ae2ed)
=> fix: improve keyboard navigation for secrets

frontend/app/[team]/integrations/page.tsx, frontend/components/syncing/CreateProviderCredentials.tsx, frontend/components/syncing/CreateProviderCredentialsDialog.tsx, frontend/components/syncing/CreateSyncDialog.tsx, frontend/components/syncing/DeleteProviderCredentialDialog.tsx, frontend/components/syncing/DeleteSyncDialog.tsx
Several UX improvements to integrations screen
* Added loading states to the delete buttons for syncs and credentials
* Added a better empty state when no credentials exist or no apps are accessible (Fixes #153):
* Added better empty state when no syncs exist -> app cards instead of dropdown menu:
Test the following states for Dev and Admin roles:
* No apps created in org
* No apps accessible by user (Dev)
* Apps create + accessible but no syncs created
* No credentials created
=> feat: integrations ux improvements

frontend/components/dashboard/CliInstallCommands.tsx
This PR fixes discrepancies between the commands printed in the code boxes and whats copied in the getting started guide in the Phase Console.
As an example - when a user ran the the MacOS install command `brew install phasehq/cli/phase` but due to a big copied  `phase/cli/phase` instead, which results in brew asking the user for their to log into their GitHub thinking its a private repository due to it being a 404.
```zsh
▶ brew install phase/cli/phase
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
asmfmt                               cekit                                helm-docs                            kin                                  magic-wormhole.rs
autobrr                              g-ls …
```
=> Fix: Phase CLI install instructions for macos brew, windows and docker

frontend/app/[team]/apps/[app]/page.tsx
Fixes an incorrectly displayed empty state on the App secrets overview screen when no secrets were present at the root path.
=> fix: incorrect empty state on secrets overview

backend/api/views.py
Enforces a leading slash on `path` strings when creating or editing secrets over REST. Also enforces a leading slash when querying secrets on a path.
=> fix: enforce leading slash when cruding secrets over rest

frontend/components/syncing/FrameworkIntegrations.tsx
This PR fixes the double slashes for the Phase Docs links in the framework integration section of the integration page.
Example: https://docs.phase.dev//integrations/frameworks/fiber
Which causes unexpected 404 like: https://docs.phase.dev/frameworks/fiber#initialize-phase-for-your-fiber-app
=> fix: integration links leading slash on docs path

frontend/utils/posthog.ts
Adds better validation for posthog host and key env vars before initializing posthog. Currently, baked values were passing a basic 'truthy' check and posthog was attempting to initialize with the placeholder values, leading to console and browser errors.
Adds extra validation to ensure `NEXT_PUBLIC_POSTHOG_HOST` is not a placeholder string before initializing posthog
Fixed posthog attempting to initialize with invalid creds
Make sure posthog correctly initializes with valid creds, and skips initializing when `NEXT_PUBLIC_POSTHOG_HOST` and `NEXT_PUBLIC_POSTHOG_KEY` are not supplied when starting the container.
=> fix: validate host and key before intializing posthog

frontend/components/environments/secrets/SecretRow.tsx
Creating a new secret in the console often requires manually revealing the value to see what is typed / pasted. This gets particularly annoying when creating multiple secrets.
Reveal the value when creating a new secret. Mask it once changes are saved. 
Fixes #193 
[Screencast from 02-27-2024 11:52:38 AM.webm](https://github.com/phasehq/console/assets/6710327/940eb4cc-e8a0-4544-8851-d13240913c64)
Automatically reveal secret value when creating a new secret
Should this be a workspace / Organisation level setting in the future? Some users may prefer the original behavior, particularly if working in public, screen sharing etc.
* Create a secret
* Observe that the value is automatically revealed
* Observe that the value is automatically masked once the secret is saved on the server
~~- [ ] …
=> feat: reveal newly created secrets

backend/api/emails.py, backend/api/templates/backend/api/email_templates/user_joined_org.html, backend/backend/graphene/mutations/organisation.py
A couple of minor fixes and improvements to emails
* Fixed a bug in the "User joined" email template that caused the `invited_by` variable to not be set correctly
* Added `Phase` as the sender name
* Fixed a typo in code
* Fixed `invited_by` template var in "User joined" email
* Added sender name to Phase Console emails
* Invite a user to an organisation
* Accept the invite
* Check that the email sent to the org owner has the correct `invited_by` value
=> fix: email fixes

frontend/app/page.tsx, frontend/contexts/organisationContext.tsx
When navigating back to the app root via the browser back button and switching to a different organisation, router loop was triggered, switching between the previously and currently select orgs
Fixed the regression by correctly resetting the `activeOrganisation` state when return to the app root
Fixed a bug with navigation when returning to the app root and picking a different Organisation workspace
* Sign in to an account with multiple Org memberships
* Pick a Org workspace from the workspace selection screen 
* Click 'Back' in the browser
* Choose a different Org workspace
=> fix: set active org to null when returning to app root

backend/backend/graphene/mutations/app.py
Upgrading a user to Admin in certain cases would result in duplicate `EnvironmentKey` instances being created, breaking the App and Environment queries for that User.
Update the `AddAppMemberMutation` mutation to use `update_or_create` to update existing EnvironmentKeys where they exist, instead of creating duplicates
Fixed a bug with User Environment Keys when updgrading a user to Admin
* Add a Dev user to an App, and give them access to one or more Environments
* Upgrade the User to Admin from the Organisation Members screen
* Login as the Admin User and make sure all Apps and Envs are accessible
=> fix: prevent duplicated env keys when upgrading user to admin

backend/api/serializers.py
Organisation context information is missing in the REST api response when authenticating
Adds a `organisation` field to the rest api response for the tokens api
The tokens api now returns the following field at the top level of the response:
```
"organisation": {
"id": "9b4e61a0-9d43-4b30-bc88-fe47aa333031",
"name": "NASA"
},
```
Added organisation context to Tokens REST API
=> feat: add organisation info to tokens serializers

frontend/app/lockbox/[boxId]/layout.tsx
Fixes a typo in the lockbox meta description
=> fix: lockbox meta description apostrophe

.github/workflows/docker_builds.yml
Removed AWS ECR (Elastic Container Repository) destination
At present our GitHub actions pipeline builds and pushes the frontend and backend containers to 3 different container image repositories (Dockerhun, ghcr, aws ecr) which is a bit excessive and redundant. This PR removed the AWS ECR destination.
=> chore: removed AWS ECR

frontend/app/[team]/apps/[app]/layout.tsx, frontend/app/[team]/apps/[app]/members/page.tsx, frontend/app/[team]/apps/[app]/page.tsx, frontend/app/[team]/apps/[app]/settings/page.tsx, frontend/app/[team]/apps/[app]/tokens/page.tsx, frontend/app/[team]/apps/page.tsx, frontend/app/[team]/integrations/page.tsx, frontend/app/[team]/members/page.tsx, frontend/app/[team]/page.tsx, frontend/components/apps/NewAppDialog.tsx, frontend/components/layout/Navbar.tsx, frontend/graphql/queries/syncing/GetOrgSyncs.gql
Several page components rely on `organisation.id` from the `OrganisationContext` to be available before performing their initial queries. This is being achieved by a combination of `useEffect` that depends on the context value to the truthy, and the query being executed with `useLazyQuery`
Replace the combination of `useEffect` and `useLazyQuery` with just a standard `useQuery`. Use the `skip` argument to prevent querying data till the context value is present.
This will simplify the code and should make data fetching on most pages slightly faster.
Improved client-side query performance on several page routes
Verify that initial queries are correctly executed and data is fetched on the following page routes / components:
* Apps
* Integrations
* Members
* App Home
* App Members
* App …
=> refactor: replace unncessary use of useLazyQuery

frontend/app/[team]/apps/[app]/page.tsx, frontend/app/[team]/apps/page.tsx
Fixes a couple of errors with graphql queries in the apps list and overview pages
* Fixed the `skip` argument in the `GetApps` operation that was incorrectly added with query args. This fixes the "variable not provided" error when hard refreshing the Apps page
* Updated the fetch policy for the `GetAppEnvironments` operation. This fixes an issue when creating an app with example secrets showed "0 secrets" in the Environment cards when opened.
Fixed error when refreshing apps page:
[Screencast from 03-27-2024 01:50:26 PM.webm](https://github.com/phasehq/console/assets/6710327/5a659c12-3c95-40b6-9124-3b3961c5f372)
Fixed secret counts when creating app with example secrets:
[Screencast from 03-27-2024 01:53:22 PM.webm](https://github.com/phasehq/console/assets/6710327/3222e478-9951-41ce-b757- …
=> fix: app queries

frontend/app/[team]/recovery/page.tsx, frontend/app/invite/[invite]/page.tsx, frontend/app/signup/page.tsx, frontend/components/layout/Sidebar.tsx, frontend/components/onboarding/AccountPassword.tsx, frontend/components/onboarding/Stepper.tsx, frontend/graphql/mutations/createOrganisation.gql
Release [v2.12.0](https://github.com/phasehq/console/releases/tag/v2.12.0) added support for storing sudo passwords in browser storage for more seasmless management of user keyrings. However, storing a password locally can only done via the unlock keyring dialog, but not when onboarding.
Add an option to save the sudo password locally on the device that a user onboards from. This can further improve the UX for managing user keyrings by removing the need to manual password entry immediately after onboarding.
[Screencast from 03-29-2024 04:14:21 PM.webm](https://github.com/phasehq/console/assets/6710327/c1bb224f-8457-4e9d-9e35-93f63c6fd2c8)
* Added an option to remember the user sudo password when signing up or joining on organisation.
* Misc UI cleanup to sidebar
* Automatically redirect …
=> feat: allow remembering sudo password when onboarding

frontend/app/invite/[invite]/page.tsx, frontend/app/signup/page.tsx
Release v2.17.0 added automatic redirection to the organisation home once onboarding was complete, however new users with no active memberships were getting redirected back to the signup page
Refetch the organisation memberships query once onboarding is complete is allow redirection to org home.
Fixed a bug when signing up that caused redirection back to signup instead of org home for new users. 
* Signup with an account that has no existing phase org memberships. Check that you are correctly redirected to org home.
* Accept an invite with no prior phase org memberships. Check that you are correctly redirected to org home.
=> fix: refetch organisation list on signup

frontend/app/webauth/[requestCode]/page.tsx, frontend/components/common/Input.tsx
CLI authentication with webauth requires manual entry of the sudo password even when the password is stored locally on the device.
Prefill the password field with the stored password when available. 
Updated webauth page to use the stored device password when available to prefill the password field.
If a user only has a single organisation membership and a saved password, should we automatically trigger authentication without a manual click of the "Login" button?
Test webauth flow for accounts with a locally stored password
=> feat: use stored device password for webauth

frontend/app/layout.tsx, frontend/package.json, frontend/tailwind.config.js, frontend/yarn.lock
* Adds JetBrains Mono for use as the monospace font across the console
* Clean up the next/font and tailwind config
* Removed `@next/font` usage and dependency
* Set `font-sans` as the default font type
Updated the monospace font to JetBrains Mono
=> feat: use jetbrains mono, update tailwind font config

backend/api/serializers.py
Fixes a bug with the `PersonalSecretSerializer`
Set the correct `sse` context to the PersonalSecretSerializer when resolving secret overrides.
Fixes a bug with personal secrets that affected the CLI and API
Ensure that overrides are correctly resolved / returned in both the CLI and API when using a PAT
=> fix: set correct sse context in personal secret serializer

backend/api/templates/backend/api/email_templates/user_joined_org.html, frontend/app/[team]/members/page.tsx, frontend/components/common/Input.tsx
Users currently need to complete their onboarding and join an Organisation before they can get cryptographic access to any Environments, making the "App access" selection when creating the invite unnecessary.
* Removed "App access" option when creating an invite for a User to join an Organisation
* Improved the UI and copy when creating an invite
* Updated the email copy sent when a user joins an Organisation to inform admins / owners to grant the new user the required access.
Miscellaneous improvements the invite process for adding new members to an Organisation
* Test the invite process for any bugs, including the email invite link
=> feat: improve org invite flow

backend/api/templates/backend/api/email_templates/user_joined_org.html, frontend/app/[team]/members/page.tsx, frontend/components/apps/NewAppDialog.tsx, frontend/components/common/Input.tsx
Removed secret placeholder example comments from most of the secrets in development, staging and production. To make the sample secret environment more cleaner.
Here's what a fresh development with sample secrets looks like:
=> Removed placeholder comments from sample secrets

frontend/app/[team]/apps/[app]/members/page.tsx
When cold-opening or hard refreshing the app "Members" tab, the `GetOrganisationMembers`  operation is run with a null `orgId` resulting in an error toast.
Skip the query till the `OrganisationContext` value is populated.
Fixed a bug when querying Organisation members from the App Members tab
Check that there is no error with graphql queries when hard refreshing the App Members tab.
=> fix: skip app members query while org context is null

frontend/pages/api/auth/[...nextauth].ts
The nextauth `jwt` callback currently add all response headers from the backend authentication POST request to the signIn response from Next.js. This causes several issues during authentication, mainly "Secure connection failed" errors on firefox that require downgrading to HTTP/1.1 in some cases.
Selectively add only the required headers to the response, i.e the `set-cookie` header in this case. This should fix the "Secure connection failed" errors on firefox with error codes `NS_ERROR_NET_INTERRUPT` and `NS_ERROR_PARTIAL_TRANSFER`. This will also allow internal api calls between the frontend Node.js server and the backend Django API on `http://backend:8000` for example.
Fixes #232 
Fixed an issue with response headers during authentication that caused "Secure connection failed" errors …
=> fix: only add set-cookie header to signin response

backend/api/urls.py, backend/api/views.py, backend/api/views/auth.py, backend/api/views/graphql.py, backend/api/views/kms.py, backend/api/views/lockbox.py, backend/api/views/secrets.py, backend/backend/urls.py
Currently the REST API only returns a simple count of the number of secrets created or updated. This requires re-fetching secrets after a POST or PUT to get the new uuids or updated properties.
Return the created or updated secrets in full.  Fixes #243 
A POST or PUT will now return the created or updates secrets in a json array:
```json
[
{
"id": "22ff660b-ad07-4bd2-9e17-01f31d009a8b",
"key": "DB_NAME",
"value": "postgres",
"comment": "primary db name",
"tags": [],
"override": null,
"path": "/backend",
"keyDigest": "b7829e56ae94313fde941350b39e3440bbc176b3dc41933a8ff38bf03ee66c3c",
"version": 1,
"createdAt": "2024-05-01T07:45:43.743793Z",
"updatedAt": "2024-05-01T07:45:43.743802Z",
"environment": "ce46fc41-f41b-428a-89a4-9eaa9564a5f1",
"folder": "88a61863-96d2-45e9-acc9-1d034eacd3f1"
}
] …
```
=> feat: return secret data when creating or updating secrets over REST API

frontend/components/environments/secrets/SecretRow.tsx
Fixes a regression that caused newly created secrets to not be revealed by default. This was introduced in the "global reveal" feature
[Screencast from 05-23-2024 07:02:36 PM.webm](https://github.com/phasehq/console/assets/6710327/5102066e-188e-4068-bd50-38361caf1170)
Fixed a bug that cause newly created secrets to not be revealed by default
=> fix: default reveal regression in secret row

frontend/components/apps/tokens/CreateServiceTokenDialog.tsx, frontend/components/apps/tokens/CreateUserTokenDialog.tsx, frontend/graphql/queries/secrets/getAppEnvironments.gql
This PR fixes incorrect example code snippets when creating api tokens, and adds a check for app encryption mode where possible.
* Added a trailing slash and the missing `Bearer` prefix to `Authorization` headers in the example curl requests
* Added a check for the App encryption mode before allowing API service tokens to be created. If SSE is not enabled, a dialog to enable this is shown first
* Added an info alert when creating API PATs to inform users to enable SSE before being able to use the token
[Screencast from 05-29-2024 02:11:43 PM.webm](https://github.com/phasehq/console/assets/6710327/caac1bfb-91ff-4993-b7a2-6331b2bad9ff)
* Fixed incorrect example code snippets when creating API tokens
* Added a step to enable SSE (if disabled) when creating App Service tokens
The enable SSE …
=> fix: api token code snippets

frontend/app/[team]/layout.tsx, frontend/components/layout/Sidebar.tsx
Using the browser 'Back' action to switch between Organisations caused the organisation context to infinitely loop between the current and previous orgs
Use a `<Link>` to switch orgs rather than directly manipulating the context value. This will make sure the context value and route params remain in sync
Fixed a bug when using the browser 'Back' action to move between Organisations
=> fix: org navigation loop

nginx/default.conf
Enabled HTTP2 in nginx config. 
HTTP2 needs to be manually enabled on a nginx instance. HTTP2 should improve network performance for the Phase Console and the API/
```fish
λ curl -I -s --http2 https://console.phase.dev
HTTP/2 307 
```
Run the new nginx config and use any http client like curl to verify that HTTP2 is enabled.
```fish
curl -I -s --http2 https://<HOST>
```
=> feat: enable http2

docker-compose.yml
The `BACKEND_API_BASE` in the frontend env uses `localhost` by default, which resolves within the container and doesn't allow connections to the backend.
Use `http://backend:8000` to allow the frontend container to make requests the backend within the internal network, even if the `HOST` is locahost. 
Fixes #270 
Updated the BACKEND_API_BASE to work correctly even when using `HOST=localhost`
Spin up the Console using `docker-compose.yml` and the example env
=> fix: use backend:8000 for BACKEND_API_BASE in frontend container env

backend/api/tasks.py, backend/api/utils/syncing/cloudflare/pages.py
Fixes a regression that broke Cloudflare Pages syncing. This issue was introduced in [v2.26.0](https://github.com/phasehq/console/releases/tag/v2.26.0) that added support for syncing secret comments.
Updated worker logic to handle 3-element tuples (key, value, comment) per secret.
Fixed a regression with sync jobs for Cloudflare Pages
=> fix: cloudflare syncs

frontend/components/environments/secrets/SecretPropertyDiffs.tsx, frontend/components/environments/secrets/SecretRow.tsx
* Fixes an issue with secret overrides for new secrets
* Fixes a UI issue with rendering of tags in secret history
Disabled the personal secret override button for new secrets till they are saved, since creating a secret override currently requires the secret uuid from the server.
Fixed the rendering of tags in the secret history dialog. Fixes #273 
[new-secret-override.webm](https://github.com/phasehq/console/assets/6710327/f8e393b0-f4b4-4a68-a78c-2ffa4b6bff77)
**Before**
**After**
* New secrets must now be saved before attempting to override them
* Fixed a rendering issue with secret tags in secret history
We should consider adding support for creating a secret and setting a personal override in a single operation.
=> fix: new secret overrides, tag history rendering

backend/api/views/secrets.py
Secret overrides are returned by the API but cannot be created or updated.
Add support for creating and updating personal secret overrides via the API. 
Added support for creating and updating personal secret overrides via the API
Check that overrides are created and updated correctly via the API.
Overrides can only be toggled off via the API for now. Deleting overrides can be done via the Console only. Support for deleting overrides over the API can be added in the future if required.
=> feat: add support for creating and updating secret overrides via the api

frontend/Dockerfile, frontend/next.config.js, frontend/scripts/start.sh
The frontend docker image running next js can be optimized and reduced in size by using `next.config.output="standalone"`. 
More context: https://nextjs.org/docs/app/api-reference/next-config-js/output
Use `standalone` output for nextjs to significantly reduce the frontend image size.
Reduced the frontend container size
=> chore: optimize frontend container image size

frontend/Dockerfile
Disables next js telemetry during container builds
=> chore: disable nextjs telemetry during builds

backend/api/utils/crypto.py, backend/api/views/secrets.py
The E2E encrypted secrets api accepts secrets that are encrypted client-side (by the CLI or SDKs), but there is currently no validation to ensure that the format of the encrypted data matches the phase ciphertext format. 
Add a validation check for encrypted fields sent via `POST` and `PUT` requests to make sure they are encrypted and formatted correctly. Return a `400 Bad request` error if they are malformed. 
Added validation to ensure malformed or unencrypted data cannot be saved via the E2E encrypted secrets API.
=> feat: validate private api encrypted data format

frontend/components/syncing/ProviderCredentialPicker.tsx
The credential picker doesn't correctly filter credentials by the chosen provider when creating a new sync, and auto-selects the credential of a different service.
Fix the filtering logic and `useEffect` hook that pre-selects a credential on component mount.
[Screencast from 07-19-2024 02:24:17 PM.webm](https://github.com/user-attachments/assets/2b29453a-bf72-4b7a-8a46-f7ed9ecbac00)
Fixed the credential picker pre-selecting invalid credentials when configuring a new sync.
Verify that only credentials for the chosen service are pre-selected and listed in the dropdown.
=> fix: credential picker filter logic

frontend/components/auth/UnlockKeyringDialog.tsx
This PR is a fix for the issue #200 . 
*Detail the proposed changes, including new features, bug fixes, or improvements. Explain how these changes impact the project, including any internal structure alterations or refactorings.*
Before : the `Unlock button will stay still for few seconds` like the video shown in issue #200 
Fix 
https://github.com/user-attachments/assets/6385906c-676d-40ae-991f-ffe378e4540d
*Summarize the changes in a user-friendly manner. Highlight new features, bug fixes, and any breaking changes, including migration steps or deprecated functionalities.*
*If there are aspects of the changes that you're unsure about or would like feedback on, list them here.*
*Describe the testing strategy. List new tests added, existing tests modified, and any testing gaps.*
*Guide the …
=> Fixed the spinner for `Unlock User Keyring`

backend/backend/graphene/types.py, frontend/apollo/graphql.ts, frontend/apollo/schema.graphql
Adds `environments` as a query-able field to the `AppType`, to facilitate fetching environments along with apps in a single query
```graphql
query GetApps($organisationId: ID!, $appId: ID) {
apps(organisationId: $organisationId, appId: $appId) {
id
name
identityKey
createdAt
sseEnabled
environments {
id
name
}
}
}
```
Adds support for querying `environments` as a list of `EnvironmentType` objects in the `AppType`
The sort ordering for environments will need to be added after the merge of #303 
=> feat: add environments to app type

frontend/app/invite/[invite]/page.tsx
Fixed temporary message of "Something went wrong" while accepting invite. 
Fixes #207 
Used `called` property of `useLazyQuery` to check if the `verifyInvite` was ever called. Through this the `Loading` element can be rendered until `called` is true, which happens only after `verifyInvite` is invoked
_Issue was caused due to initial value of `loading` in  Invite element. As data is null and loading is true in the first mount, hence `invite` is null which causes render of `Invalid Invite`_ 
During Issue:
After Fix:
Modify the Invite element to render `Loading` until `verifyInvite()` is invoked.
Create a member invite and paste that link into new tab.
=> Fix temp display of Something went wrong in invite

backend/Dockerfile, backend/constraints.txt
A recent update to `setuptools` which remove the `test` command causes `autobahn` to fail installs:
https://github.com/pypa/setuptools/issues/4519
https://github.com/crossbario/autobahn-python/issues/1644
Constrain `setuptools` to version `72` to allow `autobahn` to install correctly.
* Added a `constraints.txt` file 
* Updated the backend Dockerfile to use the `contraints.txt` file when running `pip install`
Fixed a broken dependency issue with setuptools and autobahn
=> fix: constrain setup tools version to fix broken build

frontend/app/[team]/layout.tsx
The scroll bar in the team's page gets hidden due to Navbar having `position: fixed`, therefore only scrollbars of parent elements could be visible. 
This PR fixes the issue of scrollbar being hidden on top.
Fixes #301 
Created a `div` that contains an empty div and div of children in layout of `[team]`, which is restricted to screen height. Now, only the `div` containing children can overflow making sure it to shows under `Navbar`.
After fix:
Restrict the children div to show under Navbar.
1. Run the app locally.
2. Visit the organization's home page.
=> fix: Nav bar hidding the underneath scrollbar

frontend/components/apps/EnableSSEDialog.tsx
This PR addresses an issue where the application's owner is unable to enable Server-Side Encryption (SSE) due to an incorrectly hardcoded admin check. The current implementation always treats the user as a non-admin, preventing legitimate owners and admins from enabling SSE.
- Update the `activeUserIsAdmin` check in the `EnableSSEDialog` component to properly evaluate the user's role based on the organization context.
- Ensure the `userIsAdmin` function from `@/utils/permissions` is correctly utilized.
- Verify and adjust the `organisationContext` to properly pass down the user's role.
```ts
export const userIsAdmin = (role: string) =>
['admin', 'owner'].includes(role.toLowerCase()) ?? false
```
Permissions:
Before the fix (as a `Owner` or `Admin`):
After the fix (as a `Owner` or …
=> fix: application sse permission validation

backend/ee/billing/stripe.py
Includes the current seat count when creating a customer on stripe
=> fix: include current seat count when creating stripe customer

backend/backend/urls.py
Simplified backend health endpoint by removing the unnecessary UUID.
New health endpoint:
`/health`
=> fix: removed uuid from health endpoint

frontend/middleware.ts, frontend/pages/api/auth/[...nextauth].ts, frontend/pages/api/health.ts
Added a simple `/api/health` health endpoint that returns a `{"status": "OK"}` with a http `200 OK` status.
- Modify the NextAuth configuration to bypass authentication for the `/api/health` endpoint.
- Add a new `/api/health` endpoint that returns a simple status response.
- Update the health check handler to utilize the new NextAuth configuration.
- Added a new `/api/health` endpoint that returns a `{"status": "OK"}` response.
- This endpoint is accessible without authentication, making it suitable for use with load balancers and monitoring systems.
- Should we include any additional information in the health check response, such as the application version or current server time?
- Added unit tests for the new health endpoint to ensure it returns the correct response and status code.
- …
=> Add health endpoint

backend/backend/graphene/types.py
The the EnvironmentType `members` field incorrectly returns members who are soft-deleted from an Organisation
Update the resolver to only return active members
Fixed a bug that  showed incorrect Environment members in the Manage Environment dialog
Test that the "Members" of an Environment are correctly listed:
* Add a member to an environment
* Observe that they are listed in the Members list
* Delete the member from the organisation
* Observe that they are no longer listed in the Members list
=> fix: environment members resolver returning soft-deleted users

frontend/components/UserMenu.tsx, frontend/components/layout/Sidebar.tsx, frontend/components/users/RoleLabel.tsx
This pull request addresses multiple UI issues in the UserMenu component:
1. Alignment of the role label (e.g., ADMIN) next to the user's name.
2. Text truncation for long organization names and email addresses.
3. Overall layout improvements for better readability and consistency.
Fixed: https://github.com/phasehq/console/issues/326
- Modified the UserMenu component to improve the alignment of user information
- Adjusted the flex layout to ensure the role label appears directly after the user's name
- Implemented text truncation for long organization names and email addresses
- Increased the width of the dropdown menu to accommodate more content
- Improved the overall visual consistency and responsiveness of the user dropdown menu
[Before]
[After]
- Improved UI: The user role label in …
=> Truncate long org names and user menu improvements

frontend/tests/utils/crypto/secretSharding.test.ts
Secret sharding test suite was experiencing frequent failures in the "cannot reconstruct secret with a corrupted share" test. This PR fixes it.
- Simplified the "cannot reconstruct secret with a corrupted share" test
- Implemented a more deterministic corruption method
- Focused on detecting any inconsistency in secret reconstruction, regardless of corruption degree
- Modified the "cannot reconstruct secret with a corrupted share" test
- The test now corrupts a single bit of the share, which is the minimum possible corruption
- Verified that the test fails consistently when it should and passes when the implementation is correct
- No new tests added, but the existing test's reliability has been significantly improved
1. Check out this branch
2. Run `yarn install` to ensure all …
=> fix: share corruption test

frontend/app/invite/[invite]/page.tsx, frontend/app/signup/page.tsx, frontend/components/onboarding/AccountPassword.tsx
The password feedback returned from `zxcvbn` is often incorrectly formatting resulting in typos. This PR improved the presentation of said feedback in the form of dynamic bullet points in the info box. 
This PR addresses some of the feedback from Graham in our Slack: https://phase-community.slack.com/archives/C05F92D60HE/p1717838191385539
- Simplify the password strength feedback rendering by directly mapping over the suggestions provided by zxcvbn.
- Fixed typos and grammar
Before:
After:
1. Check out this branch and dev server
4. Navigate to the signup screen / password recovery page
5. Test various password inputs, ensuring that:
- Password strength is correctly displayed
- Suggestions appear as bullet points when the password is weak
- The "Strong password" message appears for strong …
=> feat: improved formatting of signup sudo password feedback

frontend/components/environments/secrets/SecretPropertyDiffs.tsx, frontend/graphql/queries/secrets/getSecrets.gql
This pull request addresses the issue of missing secret path diffs in the secret history view, as reported in https://github.com/phasehq/console/issues/194.
- Added a new condition to check for path changes between history items
- Implemented a new section in the `SecretPropertyDiffs` component to display path diffs
- Added `path` to getSecrets graphql queries
- Should we implement a "Restore" functionality for path changes, similar to value changes? - This would require changes in the way we deploy secrets across folders.
- The new condition for path changes in the `SecretPropertyDiffs` component
- Styling consistency with other diff sections
- Potential edge cases where path diffs might not render correctly
1. Navigate to a secret with history
2. Make changes to a secret's path (via the …
=> Feat  add secret path diffs

dev-docker-compose.yml, docker-compose.yml, staging-docker-compose.yml
This PR adds a health check to all the docker compose postgresql container configs along with readyness dependency to the backend container. This will ensure that postgresql is up and running, relevant users have been created before the backend starts making connections.
=> feat: added postgres health check and readyness dependency

frontend/package.json, frontend/yarn.lock
Bump posthog dependency to the latest version `1.167.0`.
=> chore: bump posthog

frontend/app/[team]/settings/page.tsx, frontend/components/ReleaseInfo.tsx, frontend/next.config.js
The release info widget fails to fetch the latest releases due to a CSP restriction, and has bugs with its layout and positioning.
* Added `https://api.github.com` to the CSP whitelist
* Fixed the layout and positioning
Fixed release info widget in Console settings
=> fix: release info widget

frontend/components/layout/Navbar.tsx
Long application names, environment names, and other elements in the navigation bar currently overflow their containers, leading to layout issues. This affects the UI's cleanliness and usability, particularly with longer text strings.
- Added CSS-based text truncation for navigation elements that can overflow
- Implemented flexible width handling while maintaining the navbar's existing structure
- Added `shrink-0` to fixed elements (logo, separators) to preserve their dimensions
- Applied `text-ellipsis` to truncatable elements while allowing them to expand when space permits
**Before:**
**After:**
- Fixed UI issue where long application names and environment names would overflow in the navigation bar
- Improved responsive behavior of navigation text elements
Test cases to verify:
- Very …
=> feat: truncate text in navbar

frontend/app/[team]/recovery/page.tsx
Fixes an issue with the recovery process incorrectly proceeding even when an incorrect recovery phrase is entered. 
Add an early return when an incorrect recovery phrase is entered, to prevent further code execution
=> fix: add early return during account recovery if keys are incorrect

backend/ee/billing/webhooks/stripe.py
Correctly handles the Stripe subscription.created event via a webhook. Correctly updates the organisation stripe subscription id and plan tier.
Fixed a bug with Stripe self-checkout not correctly upgrading the org to Pro tier.
=> fix: handle stripe subscription created webhook

backend/Dockerfile, frontend/scripts/start.sh
Adds dual stack (IPv4/v6) networking support for frontend and backend application servers.
This is important for services like Railway that only support routing IPv6 traffic over a private network.
=> feat: listen to connections on ipv4/v6

frontend/components/settings/organisation/UpsellDialog.tsx
Fixes the seat count in the preview when upgrading to pro via self-checkout. This is related to the schema change in https://github.com/phasehq/console/pull/393/commits/323d47d58c268721567d9433a162d1a945808667
Fixed a bug with Stripe self-checkout for Phase Cloud
=> fix: seat count in self checkout price preview

frontend/components/apps/DeleteAppDialog.tsx
This PR updates the DeleteAppDialog component to improve user experience by displaying the actual app name in the confirmation input field's placeholder text, rather than using a static "MyApp" placeholder. This change makes it clearer to users which app they're about to delete.
- Modified the input placeholder in DeleteAppDialog to dynamically use the app name passed via props
- Removed hardcoded "MyApp" placeholder text
- Maintains all existing delete confirmation functionality and validation
- Manually tested with various app names to ensure placeholder updates correctly
- Verified that delete confirmation validation still works as expected
Please focus on:
- DeleteAppDialog component changes (single line modification)
- Verify that the placeholder text properly updates based on the …
=> feat: add app name in the input placeholder

frontend/apollo/client.ts, frontend/package.json, frontend/yarn.lock
The console leverages the `pollInterval` option on the apollo client's `useQuery` hook on various screens to ensure that the user always sees the most recent data, such as sync status, secrets, etc. This works, but causes significant client and server load on aggregate during very long sessions where much of the polling is not required due to the tab or window being either hidden or out of focus.
Skip polling attempts when the tab is hidden or out of focus. This is accomplished via the new `skipPollAttempt` option for `useQuery` in apollo-client `3.9.0`
https://github.com/user-attachments/assets/c535d3ba-cb9d-43a3-905f-d4b962304c2e
Skip polling the backend on various screens when the Console is hidden or out of focus
~~Should polling continue when the document is out of focus but not …
=> feat: active polling

frontend/app/webauth/[requestCode]/page.tsx, frontend/components/dashboard/CliCommand.tsx
This PR improves the CLI authentication error handling by providing clearer, step-by-step instructions when the webauth authentication fails. The changes help users seamlessly switch to token-based authentication, with specific guidance for both Phase Cloud and self-hosted deployments.
- Enhanced the error state UI with a numbered step-by-step guide
- Added separate flows for Phase Cloud and self-hosted environments
- Implemented copyable fields for email and host information
- Updated styling to match Phase's design system
- Added direct links to CLI documentation for additional help
On Phase Cloud:
On self-hosted:
Manually tested:
- Cloud hosted environment authentication flow
- Self-hosted environment authentication flow
- Token display and copying functionality
- Browser compatibility …
=> feat: webauth improvements

frontend/app/[team]/layout.tsx
There are currently 2 `<ToastContainer/>`s for react-toastify. One at the root layout, and one within the `[team]` layout which is theme-aware. This causes a [client-side exception](https://github.com/fkhadra/react-toastify/issues/1051) when a toast originating in the root layout container is still active, and the route changes to `[team]/*`. This was most commonly experienced during signup, when redirecting to the org home page.
Remove the nested toast container in the team layout. 
Fixed a bug during signup that cause a client-side exception.
Run through the signup process. Observe that the toast drawn on signup remains active once redirected to org home, and no client-side exception occurs
This change makes toasts 'dark' theme regardless of the console theme selection. We will revisit …
=> fix: client-side exception during signup due to nested toast container

frontend/components/environments/secrets/HistoryDialog.tsx, frontend/components/environments/secrets/SecretPropertyDiffs.tsx
Misc cleanup for secret history optimization
=> fix: misc cleanup for secret history optimization

backend/api/utils/rest.py
When the REST api is accessed with a deleted token, it incorrectly errors out with a status `500` code. This due to the token's `DoesNotExist` exception not being handled correctly during the intial token validation check
Gracefully hande `DoesNotExist` errors and return status `403` response
Fix a bug with REST api authentication when using deleted tokens
=> fix: gracefully handle DoesNotExist exceptions for tokens

backend/backend/graphene/queries/quotas.py
The seat counts for users and service accounts is incorrectly displayed in certain situations.
Fix the seat count calculations in the `OrganisationPlan` resolver
Fixed a bug that caused incorrect seat counts to be displayed on various screens in the Console
Verify that the seat counts in the Settings > Usage section are correct
Verify that the seat counts in the self checkout screen are correct
=> fix: seat count calculation in plan detail resolver

frontend/ee/billing/ProUpgradeDialog.tsx
Updated checkout copy to say Accounts instead of Users for consistency and clarity.
=> fix: use accounts instead of users for better clarity

frontend/app/[team]/apps/page.tsx
Fixes #405 
Added an empty state when a user:
* Has `Apps:read` permissions
* Does not have access to any apps yet
Added an empty state for users who don't have access to any apps.
Verify that the correct empty states are shown when the user:
* Has access to no apps, but has `Apps:read` permissions (this is the primary fix for the target issue)
* Has access to no apps, but has `Apps:create` permission (should see create app button isntead)
* Does not have `Apps:read` permission (Should see "access restricted" empty state instead)
=> fix: add an empty state when user doesn't have access to any apps

backend/ee/billing/graphene/queries/stripe.py, frontend/apollo/graphql.ts, frontend/apollo/schema.graphql, frontend/components/settings/organisation/PlanInfo.tsx, frontend/ee/billing/ProUpgradeDialog.tsx, frontend/ee/billing/StripeBillingInfo.tsx, frontend/graphql/queries/billing/getSubscriptionDetails.gql
Misc updates for the new pricing model
* Update the checkout screen to show price calculation based on the new pricing model
* Removed the feature list from the settings screen
* Updated the active subscription display to show the amount for the next payment
Misc updates to billing management 
* Verify that the checkout preview calculations are correct, and match the pricing page
* Verify that the $ amount shown for the next payment is correct
=> feat: updated pricing and billing

frontend/components/environments/ManageEnvironmentDialog.tsx
This PR fixes the link of the Manage access button in the Environment management modal. The previous link was routing to `<Link href={`/${organisation.name}/apps/${props.environment.app.id}/members`}>` which used to be the legacy members tab which now returns a 404.
=> fix: manage access link

frontend/components/settings/account/ViewRecoveryDialog.tsx
This PR makes improves the UX around viewing recovery kit in the settings screen.
- Added exception handling when an incorrect sudo password has been entered by the user
- Added a spinner on the `Unlock` button to show a loading indicator when users entered a sudo password and clicks Unlock
https://github.com/user-attachments/assets/8c52dc83-d4a2-4438-8cc5-7ffcfeadae56
Improved Phase recovery kit UX
- Navigate to the settings screen and try to access the recovery kit, with a valid / invalid sudo password
- A 100ms delay has been added to the Unlock button state for DX reasons. Without it the Unlock button seems to execute the decryption process swiftly, but with the just the right amount of delay (disabled) state to potentially confuse the user.
```ts
await new Promise(resolve => …
```
=> feat: improved recovery kit ux

frontend/app/[team]/apps/[app]/_components/AppSecrets.tsx, frontend/app/[team]/apps/[app]/_hooks/useAppSecrets.ts
Fixes an edge case bug and cleans up refetching logic for the new cross-env screen in app home
* If a 'deploy' operation deleted all secrets in the app, the client state update was incorrectly ignored. This has been fixed to update the state based on the network response, even when the list of secrets is empty
* Removed redundant logic for handling refetches
Fixed a bug in the cross-env screen in app home that would cause the client to display the wrong state in certain situations
* Create one or secrets in the app
* Delete all secrets and hit deploy, such that the resulting state after this operation would be an empty app
* Observe that the state correctly updates after the refetch event
~~- [ ] Regenerate graphql schema and types …
=> fix: app secrets refetch 

frontend/components/access/AccessTemplateSelector.tsx, frontend/components/access/ManageRoleDialog.tsx
Bug: It was possible to change the local UI state of the access policies of roles managed by Phase by clicking on the drop down. This change was entirely local in the users browser and did not effect any state on the backend. 
Fix: Disable edits on managed role's access policy drop down.
=> Fix: disable state for managed roles access policy permissions

frontend/app/[team]/access/service-accounts/[account]/_components/CreateServiceAccountTokenDialog.tsx, frontend/app/[team]/access/service-accounts/[account]/page.tsx, frontend/components/common/GenericDialog.tsx
Fixes an issue where the service account token dialog closes prematurely when creating the first token.
* Replace the 2 conditionally rendered dialogs with a single dialog component instance
* Trigger the dialog open state externally via conditionally rendered simple buttons
https://github.com/user-attachments/assets/cd4c1b97-51e3-4df0-a680-79e5e73e450b
Fixed an issue that caused the Service Account token dialog to close prematurely when creating the first token
The `GenericDialgog` has been updated:
* the `buttonVariant` prop is no longer required (defaults to `'primary'`
* the `buttonContent` prop is no loner required (Can be excluded to skip rendering a button)
* `openModal` is exposed for external triggering of the dialog
~~- [ …
=> fix: service account token dialog behavior

frontend/app/[team]/integrations/page.tsx
Update the Apps in the integration page on load to prevent stale App data from being served.
=> fix: use cache + network policy to fetch apps in integrations

frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx
Logs a read event for all secrets at the current path when using the "Export as .env" option to export secrets
Logs exports from the Console as a Read event for each exported secret
=> fix: log read for all secrets when exporting to .env

frontend/app/[team]/access/service-accounts/[account]/page.tsx, frontend/components/common/CopyButton.tsx
Added a label to Service Account Token ID & App ID. This make it clear that is in-fact an ID and not a secret. This adds a subtle distinction and avoid confusion among users.
=> feat: added a label to service account token ID

frontend/components/contextSnippets/ProgrammaticAccessMenu.tsx, frontend/components/contextSnippets/SecretsOneLiner.tsx
Renamed the Access button to One-click Access for better clarity. This provide a better description for what the button is for and also avoid overlap with the App Access tab which deals with things related to Access Control.
=> feat: renamed the one click access button for clarity

backend/api/views/auth.py
Adds a verbose error message when authentication fails due to an invalid or expired token for the tokens api
```bash
Error: 🚫 Not authorized.
```
```bash
Error: 🚫 Not authorized. Token expired or deleted
```
Added verbose error messages to authentication failures for the CLI
This only affects the CLI
=> fix: add error message for tokens api auth failures

backend/backend/graphene/types.py, frontend/apollo/graphql.ts, frontend/apollo/schema.graphql, frontend/app/[team]/apps/[app]/_components/AppSecrets.tsx, frontend/app/[team]/apps/[app]/_hooks/useAppSecrets.ts, frontend/app/[team]/apps/[app]/access/members/page.tsx, frontend/app/[team]/apps/page.tsx, frontend/utils/app.ts
Fixes the `EnvironmentKey matching query does not exist` error on the App > Access page. 
This was caused by the default behavior of the `EnvironmentKeyType` field resolvers for `wrapped_seed` and `wrapped_salt`, which would always try and resolve these field values for the user making the request. 
When fetching a list of environments for other users, the user making the request did not necessarily have access to all Environments, and these resolvers would throw a `DoesNotExist` error since no corresponding keys exist.
* Catch these exceptions and return `None` for these fields instead
* These fields have also been set as non-required in the schema
Fixed a bug on the App > Access page related to fetching environment scope for non-self users
~~- [ ] Update dependencies and lockfiles (if …
=> fix: app access page error

frontend/app/[team]/apps/[app]/_components/AppSecretRow.tsx
This PR makes a small quality of life improvement to make sure values are reveled upon entry for blank secrets in the cross environment screen. This allows the user to see what the value they are typing or pasting-in, making the behavior consistent with the secret creation flow.
- Updated logic to show environment secret values when newly added or modified.
- Ensured that the secret value is visible after adding a new entry.
https://github.com/user-attachments/assets/12a9d008-fa53-4031-8427-55f21f3a6133
=> fix: visibility of environment secrets

frontend/package.json, frontend/yarn.lock
Bumps Next.js to `14.2.15` to patch the middleware auth bypass vuln
=> chore: bump nextjs to 14.2.15

frontend/package.json, frontend/yarn.lock
=> chore: bump to next 14.2.25

frontend/components/apps/AppCard.tsx
Fixed: Clicking the App ID copy button would send the user to the app.
=> fix: app id ghost copy button

frontend/app/[team]/integrations/page.tsx
Fix tab index to the third party credentials so that the create credential popup is brought up for the correct provider when routed to via the App syncing tab.
=> fix:  third-party credentials create flow

frontend/components/auth/UnlockKeyringDialog.tsx
This PR improves the UI/UX for unlock user keyring via user's sudo password popup.  
- Cleaned up popup UI
- Moved the Remember password toggle from under the unlock button dropdown to under the sudo password box
- Improved error descriptions for keyring exceptions
- Fixed state reset issues after successful unlocking the keyring
=> feat: unlock keyring UI/UX improvements

frontend/app/[team]/access/network/page.tsx
Fixes the layout for network policy created / updated meta 
Display meta info inline on hover
Fixed the layout for network policy created / updated meta 
=> fix: display network policy meta inline on hover

frontend/app/[team]/access/members/_components/InviteDialog.tsx
Users can be assigned a role during the invite process before they have onboarded and set up a keyring. This causes issues with roles that contain the `ServiceAccountTokens:create` permission, as users will not have the required Service Account keys to perform this action. 
Users can be assigned these roles safely after onboarding.
Updates the list of available roles on invites to:
* Users without global access
* Users without the `ServiceAccountTokens:create`  permission
Updates the list of roles available on the user invite screen to prevent issues with creating Service Account Tokens
We are exploring a mechanism to re-enable these roles during the invite process by wrapping the require keyring server-side, before the user has onboarded. However this needs to be carefully considered to …
=> fix: restrict invite roles to prevent service account handler errors

backend/ee/billing/graphene/mutations/stripe.py
The the new standard trial period to 14 days on Phase Cloud self-serve Pro and Enterprise tiers.
- Do we need any other changes in the frontend? 
- Do we need to change anything in Stripe?
Run the Phase Console in cloud mode and test the checkout flow via test cards. Observe the trail period, make sure it's 14 days.
=> feat: updated trial period days on Phase Cloud

frontend/components/logs/SecretLogs.tsx
Misc UI fixes to the logs table and filter ui
- Replaced `Popover` with `Menu` for filter menu
- Fixed backdrop blur on filter menu on Chromium
- Fallback to skeleton loader till log row completes secret decryption operation (avoid 'undefined' in place of secret key)
=> fix: misc ui fixes to log table and filter

frontend/app/[team]/access/network/_components/ManageOrgGlobalPolicies.tsx, frontend/components/access/UpdateAccountNetworkPolicies.tsx, frontend/components/logs/SecretLogs.tsx, frontend/ee/billing/UpgradeDialog.tsx
Misc UI and copy fixes
* Fixed text wrapping and toast copy in the Account Network Access Policy dialog
* Fixed text wrapping in the Global Network Access Policy dialog
* Improved the light theme colors in the logs table
* Updated the button CTA for starting a trial in cloud mode
Misc copy and UI polish to logs and network access policy screens
=> fix: misc UI and copy fixes

frontend/ee/billing/License.tsx
This PR introduces a small quality of life improvement which allows the user to see the date and time at which their Phase License is going to expire or has expired with a on hover action.
=> feat: show license expiry date

frontend/app/[team]/apps/[app]/_components/AppSecrets.tsx, frontend/app/[team]/apps/[app]/environments/[environment]/[[...path]]/page.tsx, frontend/hooks/warnUnsavedChanges.ts, frontend/package.json, frontend/yarn.lock
It is possible to make changes to secrets and navigate way from the page before they are deployed, which loses the state of the editor. 
Warn the user when attempting to leave the page with unsaved changes to secrets, using `window.confirm()`
https://github.com/user-attachments/assets/b75ddd46-ff62-4601-8207-bf99e64aab3b
Added a warning and confirmation when leaving the app / env secrets page with unsaved changes
This currently does not work with the browser "Back" and "Forward" buttons
=> feat: warn when leaving page with unsaved secret changes

backend/ee/authentication/sso/oauth/github_enterprise/views.py
Fall back to safe values for GitHub Enterprise OAuth configuration environment values so rstrip doesn't throw an exception.
=> fix: handle missing environment variables for GitHub Enterprise URLs

frontend/app/[team]/access/service-accounts/[account]/_components/DeleteServiceAccountTokenDialog.tsx, frontend/app/[team]/access/service-accounts/_components/DeleteServiceAccountDialog.tsx
Fixes the button style on the "Delete service account" dialog
=> fix: remove ad-hoc styles on delete service account button

backend/backend/graphene/mutations/organisation.py
A redundant permission check prevents users with the `Members:delete` permission from being able to remove org members if they are not either an `Admin` or `Owner`
Remove the redundant check and respect the Role permissions.
Fixed a bug that prevented users with the `Members:delete` from being able to remove members from an org
* As a user with the `Members:delete` permission that is not `Admin` or `Owner`, verify that you are able to remove members from an org
* As a user without the `Members:delete` permission, verify that you are **not** able to remove members from an org
=> fix: remove redundant permission check when removing member from org

frontend/app/[team]/access/members/_components/DeleteInviteDialog.tsx, frontend/app/[team]/access/members/_components/DeleteMemberConfirmDialog.tsx, frontend/app/[team]/access/members/page.tsx, frontend/app/[team]/access/service-accounts/_components/DeleteServiceAccountDialog.tsx, frontend/app/invite/[invite]/page.tsx, frontend/components/common/Button.tsx
Misc fixes and improvements to account delete dialogs.
* Added loading states and more prominent account names to the Delete dialogs for User and Service Account delete actions
* Refactored the Delete Invite dialog to use a `GenericDialog`, add a toast, loading state and misc fixes to bring the styling in line with other delete dialogs
* Added a new `icon` prop to the common `Button` component. This allows an icon to be passed as prop instead of within the Button's children. This allows better conditional rendering of the icon during loading states (see demo below)
https://github.com/user-attachments/assets/c4b5349f-69c1-4f57-906c-68624e3147a2
Misc UI/UX improvements to the delete dialogs for users, invites, and service accounts.
Verify that loading states are correctly shown when …
=> fix: account delete UI and loading states

.env.dev.example, dev-docker-compose.yml
The current `dev-docker-compose.yml` has conflcting env var parsing. The `env_file` arg on each service references `.env.dev`, while the `environment` arg overrides these values and attemps to read from `.env` which might not exist
* Only read  from `.env.dev`
* Hardcode the db name and user in the postgres health check, since docker compose doesn't offer a way to reference these values from a file other than .env
* Update the instructions in the docker compose file and `.env.dev.example` for clarity
=> chore: fix dev docker compose

frontend/components/common/CommandPalette.tsx
Many users aren't aware that the command palette can be used to search for secrets globally in addition to navigating. Looking up secrets across across the entire organization is a very powerful feature. This small change make the killer feature explicit. 
Switch the command palette title from `Find something...` to ` Look up secrets..`.
=> feat: update CommandPalette title
